// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alias } from './Alias';

export type Aliases = { packs: { [key: string]: Alias }; servers: { [key: string]: Alias } };
