// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IngameStatus } from "./IngameStatus";
import type { Streamer } from "./Streamer";

export type Context = { streamer: Streamer, custom_bot_id: string, client: string, obs_status: string, bot_status: string, song_title: string, song_author: string, resource_pack_str: string, resource_packs_raw: Array<string>, server_address: string, server_raw: string, ingame_status: IngameStatus, event_loop_running: boolean, twitch_access_token: string, custom_bot_token: string, };
