// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Emote } from "./Emote";

export type Streamer = { display_name: string, id: string, color: string, avatar_url: string, emotes: Array<Emote>, };
